In [1]:
import numpy as np

In [2]:
a = np.arange(10)
b = a[2:6]
print(a, b)
b[:] = np.arange(30, 34)
print(a, b)

[0 1 2 3 4 5 6 7 8 9] [2 3 4 5]
[ 0  1 30 31 32 33  6  7  8  9] [30 31 32 33]


In [9]:
x, y = np.mgrid[range(0, 5), 0:5]
print(x, '\n', '\n' , y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]] 
 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [30]:
r = np.random.rand(5, 5)
r = r*100
print(r)

[[62.52395637 99.0843374  62.57000924 43.4207312  34.38305728]
 [60.90109967 75.96930232 47.08090368 35.95097608 84.33491265]
 [52.8981962  78.67399113 81.92361211 52.79744807 87.9838492 ]
 [36.63661256 11.89366231 92.13003446 35.54441196 34.8408997 ]
 [56.58990496 31.24815264 98.34767025 89.83760764 92.10073545]]


In [48]:
print(np.diag(range(0, 4), 0))
print(np.diag(range(0, 5), 0))

r = np.diag(r)
print(r)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
[[62.52395637  0.          0.          0.          0.        ]
 [ 0.         75.96930232  0.          0.          0.        ]
 [ 0.          0.         81.92361211  0.          0.        ]
 [ 0.          0.          0.         35.54441196  0.        ]
 [ 0.          0.          0.          0.         92.10073545]]


In [49]:
print(np.zeros(10))

print(np.ones((5,5)))

print(np.eye(4))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Считывание из файла


In [56]:
data = np.genfromtxt('stockholm_tmp.dat')

In [103]:
a = np.array(['Мцыри', 'Преступление и наказание', 'Кортик', 'Бородино', 'Молодая гвардия', 'Евгений Онегин', 'Герой нашего времени', 'Идиот', 'Зойкина квартира', 'Демон', 'Собачье Сердце', 'Сборник романов Достоевского', 'Стихотворения Лермонтова', 'Белая гвардия', 
         'Мастер и Маргарита', 'Лучшие произведения М.Ю. Лермонтова', 'Горячий снег', 'Дикая собака Динго', 'Беглец', 'Стихотворения Пушкина', 'Василий Теркин', 'Выхожу один я на дорогу', 'Война и Мир', 'Анна Каренина', 'Кинжал',
         'Севастопольские рассказы', 'Бал', 'Ангел', 'Романы Толстого', 'Князь Серебряный','Сердца Трех','По Ком Звонит Колокол', 'Марк Твен', 'Малыш и Карлсон', 'Великий Гетсби', 'Маугли',
         'Мио, Мой Мио', 'На западном фронте без перемен', 'Портрет Дориана Грея', 'Мартин Иден', 'Собор Парижской Богоматери', 'Отверженные', 'Белый Клык', 'Человек, который смеется', 'Детективы Агаты Кристи',
         'Фауст', 'Лучшие стихотворения Киплинга', 'Рубаи Омара Хайяма', 'Сонеты Уильяма Шекспира', 'Гомер: Иллиада', 'Гомер: Одиссея', 'Ворон', 'Уильям Блейк',
         'Гораций', 'Басё', 'Сборник стихотворений Гёте', 'Шиллер. Избраннные произведения', 'Сайгё', 'Сборник Роберта Бернса', 'Омар Хайям'])

size = a.size

lBooks = a[0:10]
print(size)
print(lBooks)

60
['Мцыри' 'Преступление и наказание' 'Кортик' 'Бородино' 'Молодая гвардия'
 'Евгений Онегин' 'Герой нашего времени' 'Идиот' 'Зойкина квартира'
 'Демон']
